---
- name: Change state of the incident
  servicenow.itsm.incident:
    state: in_progress
    number: "{{ snow_incident_number }}"
    other:
      comments: "{{ snow_update_comments | default(omit) }}"
  environment:
    SN_HOST: "https://{{ snow_instance }}.service-now.com"
    SN_USERNAME: "{{ snow_username }}"
    SN_PASSWORD: "{{ snow_password }}"