---
- name: Create a new incident
  servicenow.itsm.incident:
    state: new
    caller: "{{ snow_caller }}"
    short_description: "{{ snow_inc_short_desc }}"
    description: "{{ snow_inc_desc }}"
    impact: "{{ snow_inc_impact }}"
    urgency: "{{ snow_inc_urgency }}"
    other:
      category: Software
  environment:
    SN_HOST: https://{{ snow_instance }}.service-now.com
    SN_USERNAME: "{{ snow_username }}"
    SN_PASSWORD: "{{ snow_password }}"
  register: snow_incident

- name: Print incident number
  ansible.builtin.debug:
    var: snow_incident.record.number

- name: setting the ticket number in a stat for use by other playbooks
  ansible.builtin.set_stats:
    data:
      snow_incident_number: "{{ snow_incident.record.number }}"
    aggregate: "true"
